name: Build IOS
run-name: Build IOS
on:
  workflow_dispatch: {}
jobs:
  Build_IOS:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          architecture: x64
      - run: sudo xcode-select --switch /Applications/Xcode_16.4.app
      - run: flutter pub get
      - run: flutter build ios --release --no-codesign
      - name: Create IPA
        run: |
          cd build/ios/iphoneos
          mkdir Payload
          cp -r Runner.app Payload/
          zip -ry app-ios.ipa Payload
          rm -rf Payload
      - uses: actions/upload-artifact@v4
        with:
          name: app-ios.ipa
          path: build/ios/iphoneos/app-ios.ipa
  Build_MacOS:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          architecture: x64
      - run: sudo xcode-select --switch /Applications/Xcode_16.4.app
      - run: flutter pub get
      - run: flutter build macos --release
      - uses: actions/upload-artifact@v4
        with:
          name: macos-build.zip
          path: build/macos/Build/Products/Release/pica_comic.app
